# Generated by Django 3.2.9 on 2021-11-07 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signinrecord',
            options={'get_latest_by': ['sign_in__timestamp'], 'ordering': ['sign_in__timestamp'], 'permissions': [('view_report', 'Can view reports of all records')]},
        ),
    ]
