# Generated by Django 3.2.9 on 2021-11-07 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_signinrecord_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactdetails',
            options={'verbose_name_plural': 'Contact details'},
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='audit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_details', to='register.auditrecord'),
        ),
    ]
